### ISSUE TITLE
Alert box css

### ISSUE THREAD

**Issue by sureshvarman-cronj** [OpusCapita/react-alerts#1]
The CSS seems to have some problem in aligning the alert component 

With react-alerts
![image](https://user-images.githubusercontent.com/20809609/30684527-24f927b8-9ecf-11e7-9541-a22fded0435f.png)

with react-bootstrap.Alert
![image](https://user-images.githubusercontent.com/20809609/30684538-2feddfba-9ecf-11e7-9d72-37378e5d51bf.png)

**Comment by skarjalainen** [comment]
Alerts container is meant to be used in the main view of the application.
